version: "3.7"

services:
  hugo:
    container_name: hugo_${PROJECT_ID}
    environment: 
      - HUGO_THEME
      - HUGO_WATCH
      - HUGO_DESTINATION
      - HUGO_REFRESH_TIME
      - HUGO_BASE_URL
      - HUGO_PORT
    build:
      args:
        - HUGO_VERSION
        - HUGO_TYPE
      context: .
      dockerfile: ./Dockerfile
    image: ${PROJECT_ID}/hugo-dev:${HUGO_VERSION}
    ports:
      - ${HUGO_PORT}:${HUGO_PORT}
    volumes:
      - ./:/hugo
    command: tail -f /dev/null
    working_dir: /hugo/src